#!/bin/bash

# Download Maven
wget http://www.trieuvan.com/apache/maven/maven-3/3.1.0/binaries/apache-maven-3.1.0-bin.tar.gz

# Install Maven
tar xvf apache-maven-3.1.0-bin.tar.gz
rm -f apache-maven-3.1.0-bin.tar.gz

# Generate the jar file - this also runs unit tests
cd jdiff;../apache-maven-3.1.0/bin/mvn clean package

